import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../../public/assets/vendor/bootstrap/css/bootstrap.min.css";
import "./../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css";
import "./../../public/assets/vendor/aos/aos.css";
import "./../../public/assets/vendor/glightbox/css/glightbox.min.css";
import "./../../public/assets/vendor/swiper/swiper-bundle.min.css";
import "./../../public/assets/css/main.css";
import Script from "next/script";
// import "./../../public/assets/vendor/bootstrap/js/bootstrap.bundle.min.js";
// import "./../../public/assets/vendor/php-email-form/validate.js";
// import "./../../public/assets/vendor/aos/aos.js";
// import "./../../public/assets/vendor/typed.js/typed.umd.js";
// import "./../../public/assets/vendor/waypoints/noframework.waypoints.js";
// import "./../../public/assets/vendor/purecounter/purecounter_vanilla.js";
// import "./../../public/assets/vendor/glightbox/js/glightbox.min.js";
// import "./../../public/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js";
// import "./../../public/assets/vendor/isotope-layout/isotope.pkgd.min.js";
// import "./../../public/assets/vendor/swiper/swiper-bundle.min.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vimukthi Madushan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className="index-page" suppressHydrationWarning={true}>
          {children}
          <>
            <Script
              src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
              strategy="afterInteractive"
            />
            {/* <Script
              src="/assets/vendor/aos/aos.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/typed.js/typed.umd.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/waypoints/noframework.waypoints.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/purecounter/purecounter_vanilla.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/glightbox/js/glightbox.min.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/isotope-layout/isotope.pkgd.min.js"
              strategy="beforeInteractive"
            />
            <Script
              src="/assets/vendor/swiper/swiper-bundle.min.js"
              strategy="beforeInteractive"
            /> */}
            <Script src="/assets/js/main.js" strategy="beforeInteractive" />
          </>
        </body>
      </html>
    </>
  );
}
