import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../../public/assets/vendor/bootstrap/css/bootstrap.min.css";
import "./../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css";
import "./../../public/assets/vendor/aos/aos.css";
import "./../../public/assets/vendor/glightbox/css/glightbox.min.css";
import "./../../public/assets/vendor/swiper/swiper-bundle.min.css";
import "./../../public/assets/css/main.css";
import Script from "next/script";

// import "./../../public/assets/vendor/bootstrap/js/bootstrap.bundle.min.js";
// import "./../../public/assets/vendor/php-email-form/validate.js";
// import "./../../public/assets/vendor/aos/aos.js";
// import "./../../public/assets/vendor/typed.js/typed.umd.js";
// import "./../../public/assets/vendor/waypoints/noframework.waypoints.js";
// import "./../../public/assets/vendor/purecounter/purecounter_vanilla.js";
// import "./../../public/assets/vendor/glightbox/js/glightbox.min.js";
// import "./../../public/assets/vendor/imagesloaded/imagesloaded.pkgd.min.js";
// import "./../../public/assets/vendor/isotope-layout/isotope.pkgd.min.js";
// import "./../../public/assets/vendor/swiper/swiper-bundle.min.js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vimukthi Madushan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html>
        <body className="index-page">
          <header
            id="header"
            className="header d-flex flex-column justify-content-center"
          >
            <i className="header-toggle d-xl-none bi bi-list"></i>

            <nav id="navmenu" className="navmenu">
              <ul>
                <li>
                  <a href="#hero" className="active">
                    <i className="bi bi-house navicon"></i>
                    <span>Home</span>
                  </a>
                </li>
                <li>
                  <a href="#about">
                    <i className="bi bi-person navicon"></i>
                    <span>About</span>
                  </a>
                </li>
                <li>
                  <a href="#resume">
                    <i className="bi bi-file-earmark-text navicon"></i>
                    <span>Resume</span>
                  </a>
                </li>
                <li>
                  <a href="#portfolio">
                    <i className="bi bi-images navicon"></i>
                    <span>Portfolio</span>
                  </a>
                </li>
                <li>
                  <a href="#services">
                    <i className="bi bi-hdd-stack navicon"></i>
                    <span>Services</span>
                  </a>
                </li>
                <li>
                  <a href="#contact">
                    <i className="bi bi-envelope navicon"></i>
                    <span>Contact</span>
                  </a>
                </li>
              </ul>
            </nav>
          </header>
          <main className="main">{children}</main>
          <footer
            id="footer"
            className="footer position-relative light-background"
          >
            <div className="container">
              <h3 className="sitename">Brandon Johnson</h3>
              <p>
                Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni
                eligendi fuga maxime saepe commodi placeat.
              </p>
              <div className="social-links d-flex justify-content-center">
                <a href="">
                  <i className="bi bi-twitter-x"></i>
                </a>
                <a href="">
                  <i className="bi bi-facebook"></i>
                </a>
                <a href="">
                  <i className="bi bi-instagram"></i>
                </a>
                <a href="">
                  <i className="bi bi-skype"></i>
                </a>
                <a href="">
                  <i className="bi bi-linkedin"></i>
                </a>
              </div>
              <div className="container">
                <div className="copyright">
                  <span>Copyright</span>{" "}
                  <strong className="px-1 sitename">Alex Smith</strong>{" "}
                  <span>All Rights Reserved</span>
                </div>
                <div className="credits">
                  Designed by{" "}
                  <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
              </div>
            </div>
          </footer>
          <a
            href="#"
            id="scroll-top"
            className="scroll-top d-flex align-items-center justify-content-center"
          >
            <i className="bi bi-arrow-up-short"></i>
          </a>
          <div id="preloader"></div>
          <Script
            src="assets/vendor/bootstrap/js/bootstrap.bundle.min.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/php-email-form/validate.js"
            strategy="afterInteractive"
          />
          <Script src="assets/vendor/aos/aos.js" strategy="afterInteractive" />
          <Script
            src="assets/vendor/typed.js/typed.umd.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/purecounter/purecounter_vanilla.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/waypoints/noframework.waypoints.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/glightbox/js/glightbox.min.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/imagesloaded/imagesloaded.pkgd.min.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/isotope-layout/isotope.pkgd.min.js"
            strategy="afterInteractive"
          />
          <Script
            src="assets/vendor/swiper/swiper-bundle.min.js"
            strategy="afterInteractive"
          />
          <Script src="assets/js/main.js" strategy="afterInteractive" />
        </body>
      </html>
    </>
  );
}
